name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [3.9.3, 3.10.9, 3.11.11, 3.12.7, 3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk add git patch file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: cd ctags && cat patch/*.patch | patch -p1

      - run: cd ctags && ./cmakew config -d -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug
