name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  centos7:
    runs-on: ubuntu-20.04

    container: centos:7.5.1804

    steps:
      - run: yum -y update
      - run: yum -y install patch file

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'universal-ctags/ctags'
          path: 'ctags'

      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: ./cmakew --help
      - run: ./cmakew --version
      - run: ./cmakew env
      - run: ./cmakew upgrade
      - run: ./cmakew integrate zsh

      - run: cd ctags && cat patch/main-main.c.patch | patch -p1

      - run: cd ctags && ./cmakew config -x -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug

  centos8:
    runs-on: ubuntu-20.04

    container: centos:8.3.2011

    steps:
      - run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

      - run: dnf -y update
      - run: dnf -y install patch file

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'universal-ctags/ctags'
          path: 'ctags'

      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: ./cmakew --help
      - run: ./cmakew --version
      - run: ./cmakew env
      - run: ./cmakew upgrade
      - run: ./cmakew integrate zsh

      - run: cd ctags && cat patch/main-main.c.patch | patch -p1

      - run: cd ctags && ./cmakew config -x -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug
