name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  centos-7.5.1804:
    runs-on: ubuntu-20.04

    container: centos:7.5.1804

    steps:
      - run: yum -y update
      - run: yum -y install git patch file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: ./cmakew --help
      - run: ./cmakew --version
      - run: ./cmakew env
      - run: ./cmakew upgrade
      - run: ./cmakew integrate zsh

      - run: cd ctags && cat patch/main-main.c.patch | patch -p1

      - run: cd ctags && ./cmakew config -x -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug

  centos-8.3.2011:
    runs-on: ubuntu-20.04

    container: centos:8.3.2011

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-Base.repo

      - run: dnf -y update
      - run: dnf -y install patch file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: ./cmakew --help
      - run: ./cmakew --version
      - run: ./cmakew env
      - run: ./cmakew upgrade
      - run: ./cmakew integrate zsh

      - run: cd ctags && cat patch/main-main.c.patch | patch -p1

      - run: cd ctags && ./cmakew config -x -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug
