name: Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        shell: cygwin {0}

    steps:
      - run: choco install -y cygwin
        shell: pwsh

      - run: C:\tools\cygwin\bin\bash.exe --login -i -c "sed -i 's/--login -i/--login -i %1/' /cygdrive/c/tools/cygwin/Cygwin.bat"
        shell: pwsh

      - run: choco install -y --source cygwin git patch file

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v2

      - run: printf 'cd %s' "$(cygpath '${{ github.workspace }}')" >> ~/.bashrc

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: ./cmakew --help
      - run: ./cmakew --version
      - run: ./cmakew env
      - run: ./cmakew upgrade
      - run: ./cmakew integrate zsh

      - run: cd ctags && cat patch/main-main.c.patch | patch -p1

      - run: cd ctags && ./cmakew config -x -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/bin/make
      - run: cd ctags && cat build.d/CMakeFiles/CMakeOutput.log
      - run: cd ctags && cat build.d/CMakeFiles/CMakeError.log
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs html -d
      - run: cd ctags && ./cmakew test -d -V --debug --timeout 2000
