name: Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -l -i {0}

    steps:
    - run: choco install -y --source cygwin dos2unix
      shell: pwsh
    
    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2
    
    - run: printf 'cd %s' "$(cygpath '${{ github.workspace }}')" >> ~/.bashrc

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew CMakeLists.txt src patch misc ctags/
    - run: cd ctags && patch -p1 < patch/*.patch
    - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
    - run: cd ctags && ./cmakew install
    - run: file /usr/bin/ctags
    - run: /usr/bin/ctags --version
