name: Fedora

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [28, 30, 33, rawhide]

    container: fedora:${{ matrix.tag }}

    steps:
      - run: dnf --nogpgcheck -y update
      - run: dnf --nogpgcheck -y install git file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r * ctags/
      - run: cd ctags && patch -p1 < patch/*.patch
      - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
