name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/freebsd${{ matrix.version }}
        run: |
          run() {
            printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
            $@
          }
          run pkg install -y git patch file

          run git clone https://github.com/universal-ctags/ctags
          run cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/
          run cd ctags
          
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

          run ./cmakew config -d -DCMAKE_BUILD_TYPE=Release
          run ./cmakew install -d
          run file /usr/local/bin/ctags
          run /usr/local/bin/ctags --version
          run ./cmakew docs html -d
          run ./cmakew test -d -V --debug
