name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [10.15]

    runs-on: macos-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2
    
    - run: brew install jansson libxml2 libyaml

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew CMakeLists.txt src patch misc ctags/
    - run: cd ctags && patch -p1 < patch/*.patch
    - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
    - run: cd ctags && ./cmakew install
    - run: file /usr/bin/ctags
    - run: /usr/bin/ctags --version
