name: Manjaro Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: zelec/manjarolinux

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm git patch file sed

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

      - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
