name: Manjaro Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: zelec/manjarolinux

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm git patch file sed

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r cmake cmakew CMakeLists.txt src patch misc ctags/
      - run: cd ctags && patch -p1 < $(find patch -name "*.patch")
      - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
