name: MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git patch libiconv-devel

    - run: echo "$PATH"

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/
    
    - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

    - run: cd ctags && ./misc/optlib2c optlib/RSpec.ctags > optlib/RSpec.c

    - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release || (cat build.d/CMakeFiles/CMakeError.log; return 1)
    - run: cd ctags && ./cmakew install
    - run: file /usr/local/bin/ctags
    - run: /usr/local/bin/ctags --version
