name: MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: git patch libiconv-devel

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/
    
    - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

    - run: cd ctags && ./cmakew config -d -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - run: cd ctags && ./cmakew install -d
    - run: file /usr/bin/ctags
    - run: /usr/bin/ctags --version
    - run: cd ctags && ./cmakew docs html -d
    - run: cd ctags && ./cmakew test -d -V --debug
