name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15
    
    strategy:
      matrix:
        version: [8, 9]

    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/netbsd${{ matrix.version }}
        run: |
          run sudo pkgin -y install git patch file mozilla-rootcerts

          run sudo mozilla-rootcerts install

          run git clone https://github.com/universal-ctags/ctags
          run cp -r cmake cmakew CMakeLists.txt src patch misc ctags/
          run cd ctags
          run patch -p1 < patch/*.patch
          run ./cmakew config -DCMAKE_BUILD_TYPE=Release
          run ./cmakew install
          run file /usr/bin/ctags
          run /usr/bin/ctags --version
