name: openSUSE Leap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [15.1, 15.2]

    container: opensuse/leap:${{ matrix.tag }}

    steps:
      - run: zypper update -y
      - run: zypper install -y git patch file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r * ctags/
      - run: cd ctags && patch -p1 < patch/*.patch
      - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
