name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [16.04, 18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

    - run: cd ctags && cat patch/*.patch | patch -p1

    - run: cd ctags && ./cmakew config -d -DCMAKE_BUILD_TYPE=Release
    - run: cd ctags && sudo ./cmakew install -d
    - run: sudo file /usr/local/bin/ctags
    - run: sudo /usr/local/bin/ctags --version
    - run: cd ctags && ./cmakew docs html -d
    - run: cd ctags && ./cmakew test -d -V --debug
