name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [16.04, 18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
    - uses: actions/checkout@v2

    - run: git clone https://github.com/universal-ctags/ctags
    - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

    - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

    - run: cd ctags && ./cmakew config -DCMAKE_BUILD_TYPE=Release
    - run: cd ctags && ./cmakew install
    - run: file /usr/local/bin/ctags
    - run: /usr/local/bin/ctags --version
