name: VoidLinux-musl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: voidlinux/voidlinux-musl

    steps:
      - run: xbps-install -Sy git patch file

      - run: git init
      - run: git remote add origin https://github.com/${{github.repository}}
      - run: git config --local gc.auto 0
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +${{github.sha}}:refs/remotes/origin/master
      - run: git checkout --progress --force -B master refs/remotes/origin/master
      - run: ls

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

      - run: cd ctags && ./cmakew config -d -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
