name: VoidLinux-glibc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: voidlinux/voidlinux

    steps:
      - run: xbps-install -Sy git patch file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags
      - run: cp -r cmake cmakew cmakew.rc CMakeLists.txt src patch misc ctags/

      - run: |
          cd ctags
          for item in patch/*.patch
          do
            patch -p1 < "$item" || return 1
          done

      - run: cd ctags && ./cmakew config -d -DCMAKE_BUILD_TYPE=Release
      - run: cd ctags && ./cmakew install -d
      - run: file /usr/local/bin/ctags
      - run: /usr/local/bin/ctags --version
      - run: cd ctags && ./cmakew docs -d
      - run: cd ctags && ./cmakew test -d
