name: Windows-10

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        visual-studio-version: [2017, 2019]

    defaults:
      run:
        shell: cmd /C {0}

    steps:
    # https://github.com/jberezanski/ChocolateyPackages/issues/97
    - run: choco upgrade    visualstudio2019enterprise

      #- run: choco install -y visualstudio${{ matrix.visual-studio-version }}buildtools
      #if:  ${{ matrix.visual-studio-version == 2017 }}

    - run: choco install -y visualstudio${{ matrix.visual-studio-version }}-workload-vctools 
      if:  ${{ matrix.visual-studio-version == 2017 }}
    
    - run: choco install -y pkgconfiglite
    - run: choco install -y patch

    - uses: actions/checkout@v2

    - run: cd .. & git clone https://github.com/universal-ctags/ctags
    
    - run: xcopy /s /y . ..\ctags

    - run: cd ../ctags & patch -p1 -i patch/main-general.h.patch
    - run: cd ../ctags & patch -p1 -i patch/main-options.c.patch
    - run: cd ../ctags & patch -p1 -i patch/main-main.c.patch

    - run: cd ../ctags & build.bat ${{ matrix.visual-studio-version }}

    - run: cd ../ctags/output/bin & ctags --version
